version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - aws --version
      # Upgrade pip
      - pip install --upgrade pip
      # Upgrade to the latest version of AWS CLI
      - pip install --upgrade awscli
  pre_build:
    commands:
      # Download application.properties file from S3
      - aws s3 cp s3://$S3_BUCKET/application.properties src/main/resources/application.properties
      # Download config.properties file from S3
      - aws s3 cp s3://$S3_BUCKET/config.properties config.properties
      - echo "after download application file"
      - mvn clean compile test -T1C
  build:
    commands:
      - mvn -T 1C package
artifacts:
  files:
    - target/nathan-0.1.jar
    - appspec.yml
    - buildspec-docker.yml
    - Dockerfile
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'