version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - aws --version
      # Upgrade pip
      - pip install --upgrade pip
      # Upgrade to the latest version of AWS CLI
      - pip install --upgrade awscli
  pre_build:
    commands:
      - mvn clean compile test -T1C
      # Download application.properties file from S3
      - aws s3 cp s3://$S3_BUCKET/nathan/dev/application.properties target/classes/application.properties
artifacts:
  files:
    - target/nathan-0.1.jar
    - appspec.yml
    - buildspec-docker.yml
    - Dockerfile
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'