version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
  pre_build:
    commands:
      - mvn -T 1C clean install
  build:
    commands:
      - mvn -T 1C package
artifacts:
  files:
    - target/nathan-0.1.jar
    - appspec.yml
#    - buildspec-docker.yml
#    - Dockerfile
  discard-paths: yes
cache:
  paths:
    - '/root/.m2/**/*'